import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

const SEED_S = [
  {id:'s1',date:'2026-03-02',type:'gym',muscles:['Piernas','Pecho','Tríceps','Cardio'],notes:'Sentadilla 55kg×8. Banca 60kg×7. Remo Gironda 25kg.',exercises:[{n:'Sentadilla',kg:55,s:3,r:8},{n:'Press banca',kg:60,s:1,r:7},{n:'Remo Gironda',kg:25,s:3,r:6}]},
  {id:'s2',date:'2026-03-03',type:'gym',muscles:['Piernas','Pecho','Cardio'],notes:'Sentadilla 60kg×8. Banca 65kg×8.',exercises:[{n:'Sentadilla',kg:60,s:3,r:8},{n:'Press banca',kg:65,s:1,r:8}]},
  {id:'s3',date:'2026-03-04',type:'gym',muscles:['Pecho','Espalda','Bíceps','Tríceps'],notes:'Banca 70kg×4 PR. Dorsal 41kg. Curl martillo 10kg.',exercises:[{n:'Press banca',kg:70,s:1,r:4},{n:'Remo Gironda',kg:25,s:3,r:8},{n:'Curl martillo',kg:10,s:3,r:6}]},
  {id:'s4',date:'2026-03-07',type:'run',muscles:['Cardio'],notes:'14k · 5:58/km · FC 161ppm · 1.159kcal',exercises:[]},
  {id:'s5',date:'2026-03-10',type:'gym',muscles:['Piernas','Pecho','Tríceps'],notes:'Hack squat 60kg×8. Press declinado 70kg×1.',exercises:[{n:'Hack squat',kg:60,s:3,r:8},{n:'Press declinado',kg:70,s:1,r:1}]},
  {id:'s6',date:'2026-03-11',type:'gym',muscles:['Bíceps','Tríceps'],notes:'Bíceps polea 59kg×8. Drop set. Tríceps 29kg×6.',exercises:[{n:'Bíceps polea',kg:59,s:3,r:8},{n:'Tríceps polea V',kg:29,s:1,r:6},{n:'Curl martillo',kg:12.5,s:1,r:6}]},
  {id:'s7',date:'2026-03-12',type:'gym',muscles:['Espalda','Bíceps','Tríceps'],notes:'Bíceps 61kg PR. Tríceps 32kg. Curl martillo 15kg.',exercises:[{n:'Bíceps polea',kg:61,s:1,r:8},{n:'Tríceps polea V',kg:32,s:1,r:6},{n:'Remo Gironda',kg:35,s:2,r:10},{n:'Curl martillo',kg:15,s:1,r:5}]},
  {id:'s8',date:'2026-03-15',type:'trail',muscles:['Cardio'],notes:'LPA Trail 17k · 5:35/km · FC 151ppm · 4 PR',exercises:[]},
  {id:'s9',date:'2026-03-16',type:'gym',muscles:['Bíceps','Tríceps'],notes:'Bíceps 59kg. Drop set 10 reps.',exercises:[{n:'Bíceps polea',kg:59,s:3,r:8},{n:'Tríceps polea V',kg:29,s:1,r:6},{n:'Curl martillo',kg:12.5,s:1,r:6}]},
  {id:'s10',date:'2026-03-18',type:'gym',muscles:['Bíceps','Tríceps'],notes:'Tríceps kettlebell 16kg×12.',exercises:[{n:'Bíceps polea',kg:59,s:3,r:8},{n:'Tríceps polea V',kg:29,s:1,r:6}]},
  {id:'s11',date:'2026-03-19',type:'gym',muscles:['Piernas','Espalda','Bíceps','Tríceps'],notes:'Cuád 47kg backoff. Femoral 53kg×8. Bíceps 59kg×10.',exercises:[{n:'Extensión cuádriceps',kg:47,s:3,r:8},{n:'Femoral',kg:53,s:3,r:8},{n:'Bíceps polea',kg:59,s:3,r:10}]},
  {id:'s12',date:'2026-03-20',type:'gym',muscles:['Bíceps','Tríceps'],notes:'Bíceps 59kg×11 PR reps. Tríceps 29kg×8.',exercises:[{n:'Bíceps polea',kg:59,s:3,r:11},{n:'Tríceps polea V',kg:29,s:1,r:8},{n:'Curl martillo',kg:12.5,s:1,r:7}]},
  {id:'s13',date:'2026-03-23',type:'gym',muscles:['Piernas','Espalda'],notes:'Sentadilla 60kg×8 ×2. Cuád 69kg×8. Dominadas 15 reps.',exercises:[{n:'Sentadilla',kg:60,s:4,r:8},{n:'Extensión cuádriceps',kg:69,s:1,r:8},{n:'Dominadas',kg:0,s:3,r:15}]},
  {id:'s15',date:'2026-03-25',type:'gym',muscles:['Piernas','Espalda','Bíceps','Hombros'],notes:'Sentadilla 80kg×8 PR sin dolor. Cuád 65kg×10. Dominadas 15+15+10. Tracción diagonal 95kg×8+6 rest-pause. Bíceps bayesian 7.5kg. Remo mancuernas 20kg×10+5 rest-pause.',exercises:[{n:'Sentadilla',kg:80,s:3,r:8},{n:'Extensión cuádriceps',kg:65,s:3,r:10},{n:'Dominadas',kg:0,s:3,r:15},{n:'Tracción diagonal',kg:95,s:3,r:8},{n:'Bíceps bayesian',kg:7.5,s:3,r:9},{n:'Remo mancuernas',kg:20,s:3,r:10}]},
  {id:'s14',date:'2026-03-24',type:'run',muscles:['Cardio'],notes:'5,00k · 5:23/km · 26:55 · FC 136ppm (máx 147) · 395kcal · D+32m · Tempo aeróbico alto',exercises:[]},
  {id:'s15',date:'2026-03-25',type:'gym',muscles:['Piernas','Espalda','Bíceps','Hombros'],notes:'Sentadilla 80kg×8 PR sin dolor. Cuád 65kg×10. Dominadas 15+15+10. Tracción diagonal 95kg×8+6 rest-pause. Bíceps bayesian 7.5kg. Remo mancuernas 20kg×10+5 rest-pause.',exercises:[{n:'Sentadilla',kg:80,s:3,r:8},{n:'Extensión cuádriceps',kg:65,s:3,r:10},{n:'Dominadas',kg:0,s:3,r:15},{n:'Tracción diagonal',kg:95,s:3,r:8},{n:'Bíceps bayesian',kg:7.5,s:3,r:9},{n:'Remo mancuernas',kg:20,s:3,r:10}]},
  {id:'s16',date:'2026-03-25',type:'senderismo',muscles:['Cardio'],notes:'Mogán Senderismo · 6,23km · 3:00:12 · D+244m · FC 103ppm (máx 145) · 987kcal · Base aeróbica baja · 29°C',exercises:[]},
  {id:'s17',date:'2026-03-26',type:'gym',muscles:['Piernas','Espalda'],notes:'Sentadilla 80kg×9 (+1 rep). Mejor profundidad, sin dolor ingle. Cuád 59kg×13. Dominadas 15+8. Sesión incompleta pero progreso en bloque principal.',exercises:[{n:'Sentadilla',kg:80,s:3,r:9},{n:'Extensión cuádriceps',kg:59,s:3,r:13},{n:'Dominadas',kg:0,s:2,r:15}]},
  {id:'s18',date:'2026-03-27',type:'gym',muscles:['Piernas','Espalda','Bíceps'],notes:'Cuád 71kg×10 PR. Dominadas sin asistencia (20+18). Tracción 95kg×10 (techo máquina). Remo 20kg. Bayesian 7.5kg rest-pause. Sin carga lumbar.',exercises:[{n:'Extensión cuádriceps',kg:71,s:3,r:10},{n:'Dominadas',kg:0,s:3,r:20},{n:'Tracción diagonal',kg:95,s:3,r:10},{n:'Remo mancuernas',kg:20,s:3,r:10},{n:'Bíceps bayesian',kg:7.5,s:3,r:10}]},
  {id:'s19',date:'2026-03-30',type:'gym',muscles:['Piernas','Hombros'],notes:'Peso muerto 70kg×9 consolidado. Cuád unilateral excéntrico 35kg×10+10. Obli cuos polea 29kg. Core integrado. Sin sobrecarga lumbar.',exercises:[{n:'Peso muerto',kg:70,s:3,r:9},{n:'Cuádriceps unilateral',kg:35,s:3,r:10},{n:'Oblicuos polea',kg:29,s:3,r:8}]},
  {id:'s20',date:'2026-04-03',type:'senderismo',muscles:['Cardio'],notes:'Mogán Senderismo · 27,93km · 9:19:37 · D+1898m · FC 116ppm (máx 162) · 3.650kcal · Parque Natural Pilancones · 28°C',exercises:[]},
  {id:'s21',date:'2026-04-06',type:'gym',muscles:['Pecho','Piernas','Hombros'],notes:'Press banca 60kg×8 + rest-pause. Cuád 71kg×9 PR confirmado + dropset. Posterior hombro 23kg. Press militar 7.5kg. Tracción vertical 49.5kg×10.',exercises:[{n:'Press banca',kg:60,s:3,r:8},{n:'Extensión cuádriceps',kg:71,s:3,r:9},{n:'Declinado mancuerna',kg:12.5,s:4,r:14},{n:'Face pull',kg:23,s:3,r:10},{n:'Press militar',kg:7.5,s:3,r:10},{n:'Tracción vertical',kg:49.5,s:3,r:10}]},
  {id:'s22',date:'2026-04-07',type:'gym',muscles:['Pecho','Piernas','Hombros'],notes:'Press banca 60kg×6 consolidado. Cuád 71kg×10. Declinado 12.5kg constante. Posterior hombro 23kg. Tracción vertical 53kg×10 PR. Press militar 7.5kg sin molestias.',exercises:[{n:'Press banca',kg:60,s:3,r:6},{n:'Extensión cuádriceps',kg:71,s:2,r:10},{n:'Declinado mancuerna',kg:12.5,s:4,r:14},{n:'Face pull',kg:23,s:2,r:10},{n:'Press militar',kg:7.5,s:2,r:10},{n:'Tracción vertical',kg:53,s:2,r:10}]},
  {id:'s23',date:'2026-04-09',type:'gym',muscles:['Pecho','Piernas'],notes:'Press banca 60kg×7. Cuád 71kg×10. Declinado 12.5kg constante. Sesión interrumpida por molestia en hombro. Bloque 2 incompleto.',exercises:[{n:'Press banca',kg:60,s:3,r:7},{n:'Extensión cuádriceps',kg:71,s:3,r:10},{n:'Declinado mancuerna',kg:12.5,s:3,r:14}]},
  {id:'s24',date:'2026-04-10',type:'gym',muscles:['Pecho','Piernas','Hombros'],notes:'Press banca 60kg×8 mejora. Cuád 71kg×10 + dropset. Declinado 15kg×14 PR carga. Tracción vertical 53kg×10. Press militar 7.5kg estable. Sesión completa alta intensidad.',exercises:[{n:'Press banca',kg:60,s:3,r:8},{n:'Extensión cuádriceps',kg:71,s:3,r:10},{n:'Declinado mancuerna',kg:15,s:4,r:14},{n:'Press militar',kg:7.5,s:3,r:10},{n:'Tracción vertical',kg:53,s:3,r:10}]},
  {id:'s25',date:'2026-04-13',type:'gym',muscles:['Pecho','Hombros','Espalda','Tríceps','Piernas'],notes:'Post-virus. Elevación hombros 29kg×10. Tríceps polea 29kg (exceso, fallo). Femoral incompleto por fatiga. Reactivación sin forzar. Hombro sin molestias.',exercises:[{n:'Elevación hombros',kg:29,s:3,r:10},{n:'Remo Gironda',kg:0,s:3,r:0},{n:'Tríceps polea',kg:29,s:3,r:3},{n:'Extensión cuádriceps',kg:0,s:3,r:0},{n:'Femoral',kg:0,s:2,r:0}]},
  {id:'s26',date:'2026-04-17',type:'gym',muscles:['Pecho','Hombros','Espalda','Tríceps'],notes:'Empuje pecho 41kg×10. Elevación hombros 35kg×10. Remo Gironda 41kg×10. Tríceps polea 29kg×6. Sin pierna (reserva para carrera). Sesión tren superior completa.',exercises:[{n:'Empuje pecho',kg:41,s:3,r:10},{n:'Elevación hombros',kg:35,s:3,r:10},{n:'Remo Gironda',kg:41,s:3,r:10},{n:'Tríceps polea',kg:29,s:3,r:6}]},
  {id:'s27',date:'2026-04-18',type:'trail',muscles:['Cardio'],notes:'Moya Trail running · 19,48km · 2:52:02 · 8:50/km · D+946m · FC 144ppm (máx 182) · 1.872kcal · VO₂ máx (TE 5.0) · 25°C',exercises:[]},
  {id:'s28',date:'2026-04-20',type:'gym',muscles:['Pecho','Espalda','Tríceps','Piernas'],notes:'Press inclinado 15kg×10. Press francés EZ 15kg. Tracción prono 35→53kg×7 (máx 53kg). Tracción supino 41→47→59kg×6 (máx 59kg). Prensa unilateral 50kg D / 40kg I.',exercises:[{n:'Press inclinado mancuernas',kg:15,s:3,r:10},{n:'Press francés EZ',kg:15,s:3,r:8},{n:'Tracción vertical prono',kg:53,s:3,r:7},{n:'Tracción vertical supino',kg:59,s:3,r:6},{n:'Prensa unilateral',kg:50,s:3,r:10}]},
  {id:'s29',date:'2026-04-21',type:'gym',muscles:['Pecho','Espalda','Tríceps','Piernas'],notes:'Press inclinado 15kg×10 mejora. Press francés EZ 15kg×10. Tracción prono 35→53kg×6. Supino 41→59kg×6 consolidado. Prensa unilateral 40kg sin asimetría. Sesión consistente.',exercises:[{n:'Press inclinado mancuernas',kg:15,s:3,r:10},{n:'Press francés EZ',kg:15,s:3,r:10},{n:'Tracción vertical prono',kg:53,s:3,r:6},{n:'Tracción vertical supino',kg:59,s:3,r:6},{n:'Prensa unilateral',kg:40,s:3,r:10}]},
  {id:'s30',date:'2026-04-08',type:'ultimate',muscles:['Cardio'],notes:'Las Canteras · Ultimate Frisbee · 3,29km · 1:19:12 · FC 107ppm · 512kcal · 18°C',exercises:[]},
  {id:'s31',date:'2026-04-21',type:'run',muscles:['Cardio'],notes:'5k aprox · 5:23/km · 27:00 · FC 157ppm (máx 177) · 408kcal · D+6m · Umbral aeróbico alto (TE 3,8) · 22°C',exercises:[]},
  {id:'s32',date:'2026-04-22',type:'gym',muscles:['Pecho','Espalda','Tríceps'],notes:'Press inclinado 15kg×10. Press francés EZ 15kg×10. Tracción prono 47kg×6 (fatiga). Supino 53kg×8. Sesión corta ~30min, eficiente. Sin pierna.',exercises:[{n:'Press inclinado mancuernas',kg:15,s:3,r:10},{n:'Press francés EZ',kg:15,s:3,r:10},{n:'Tracción vertical prono',kg:47,s:2,r:6},{n:'Tracción vertical supino',kg:53,s:2,r:8}]},
  {id:'s33',date:'2026-04-22',type:'ultimate',muscles:['Cardio'],notes:'Las Canteras · Ultimate Frisbee · 3,66km · 1:30:05 · FC 119ppm (máx 153) · 700kcal · 26°C · 14min corriendo / 27min caminando / 48min parado',exercises:[]},
  {id:'s34',date:'2026-04-24',type:'gym',muscles:['Pecho','Espalda','Tríceps'],notes:'Press inclinado 15kg×10-11. Press francés EZ 15kg×10. Supino 59kg×9 PR reps. Sesión interrumpida por molestia hombro en prono r3. Decisión acertada.',exercises:[{n:'Press inclinado mancuernas',kg:15,s:3,r:11},{n:'Press francés EZ',kg:15,s:3,r:10},{n:'Tracción vertical prono',kg:53,s:2,r:6},{n:'Tracción vertical supino',kg:59,s:2,r:9}]},
  {id:'s35',date:'2026-04-25',type:'senderismo',muscles:['Cardio'],notes:'San Bartolomé de Tirajana · 20,63km · 7:23:25 · D+688m / D-1236m · FC 107ppm (máx 144) · 2.040kcal · 28.138 pasos · 25°C · salida 4:47h',exercises:[]},
  {id:'s36',date:'2026-04-27',type:'gym',muscles:['Hombros','Pecho','Bíceps'],notes:'Press hombros multipower 30kg×8. Press banca 60kg×6. Curl predicador 25kg×6. Circuito 4 rondas con progresión de carga.',exercises:[{n:'Press hombros multipower',kg:30,s:4,r:8},{n:'Press banca',kg:60,s:4,r:6},{n:'Curl predicador',kg:25,s:4,r:12}]},
  {id:'s37',date:'2026-04-28',type:'gym',muscles:['Hombros','Pecho','Bíceps'],notes:'Press hombros 30kg consolidado (10+10+7). Banca mejora progresiva 4→6→7 en sesión. Curl predicador 25kg×10 constante. Próxima: hombros 35kg, predicador 27.5kg.',exercises:[{n:'Press hombros multipower',kg:30,s:4,r:10},{n:'Press banca',kg:60,s:4,r:7},{n:'Curl predicador',kg:25,s:4,r:10}]},
  {id:'s38',date:'2026-04-28',type:'run',muscles:['Cardio'],notes:'5,00k · 5:55/km · 29:35 · FC 138ppm (máx 149) · 397kcal · D+4m · Base aeróbica baja (TE 3,2) · 23°C',exercises:[]},
  {id:'s39',date:'2026-04-29',type:'gym',muscles:['Hombros','Pecho','Bíceps'],notes:'Press hombros 35kg×7. Press banca 60kg×8 mejor serie. Curl predicador 25kg×8. 3 rondas por autorregulación. Sesión corta eficiente.',exercises:[{n:'Press hombros multipower',kg:35,s:3,r:7},{n:'Press banca',kg:60,s:3,r:8},{n:'Curl predicador',kg:25,s:3,r:8}]},
];

const SEED_B = [
  {id:'b1',date:'2026-02-23',peso:86.50,grasa:29.8,musculo:56.70,esq:39.9,agua:51.5,proteina:14.1,visceral:10.0,bmr:1683,edad:41},
  {id:'b2',date:'2026-03-10',peso:83.05,grasa:14.9,musculo:65.94,esq:48.8,agua:62.4,proteina:17.0,visceral:3.0,bmr:1896,edad:37},
  {id:'b3',date:'2026-03-23',peso:81.20,grasa:14.0,musculo:65.12,esq:49.3,agua:63.0,proteina:17.2,visceral:3.0,bmr:1877,edad:37},
  {id:'b4',date:'2026-04-06',peso:81.50,grasa:14.4,musculo:65.11,esq:49.1,agua:62.8,proteina:17.1,visceral:3.0,bmr:1877,edad:37},
  {id:'b5',date:'2026-04-20',peso:82.45,grasa:14.9,musculo:65.46,esq:48.8,agua:62.4,proteina:17.0,visceral:3.0,bmr:1885,edad:37},
];

const SEED_D = [
  {id:'d1',date:'2026-03-02',type:'gym',text:`<strong>Semana de arranque.</strong> Primera sesión estructurada del ciclo. Sentadilla a 55kg, tomando contacto con el patrón de movimiento. Press banca a 60kg con buena técnica. Sin molestias. Base sólida para construir.`},
  {id:'d2',date:'2026-03-03',type:'gym',text:`Segundo día consecutivo. Sentadilla sube a 60kg con control limpio. Banca a 65kg. <span class="note">Buena tolerancia a la fatiga acumulada.</span>`},
  {id:'d3',date:'2026-03-04',type:'gym',text:`<span class="pr">🔼 Primera marca de referencia: Press banca 70kg × 4.</span> Técnicamente limpia aunque cerca del límite. Bíceps y tríceps como complemento. Curl martillo a 10kg — punto de partida documentado.`},
  {id:'d4',date:'2026-03-07',type:'run',text:`<span class="note">14k a 5:58/km.</span> FC media 161ppm. Salida larga de baja intensidad. 1.159kcal. El fondo aeróbico aguanta la distancia sin problemas.`},
  {id:'d5',date:'2026-03-10',type:'gym',text:`Hack squat entrando en el bloque de pierna. Press declinado a 70kg de tanteo. Biometría del mismo día: <span class="pr">peso 83,05kg · grasa 14,9% · músculo 65,94kg.</span> Composición corporal en muy buen punto.`},
  {id:'d6',date:'2026-03-11',type:'gym',text:`Sesión de bíceps y tríceps. Polea bíceps a 59kg × 8 con drop set. Tríceps a 29kg. Curl martillo sube a 12,5kg. Trabajo de aislamiento bien ejecutado.`},
  {id:'d7',date:'2026-03-12',type:'gym',text:`<span class="pr">🔼 PR Bíceps polea: 61kg × 8.</span> Marca que se convierte en referencia del ciclo. Tríceps a 32kg, nueva carga. Remo Gironda a 35kg. Curl martillo llega a 15kg. <strong>Semana muy productiva en tren superior.</strong>`},
  {id:'d8',date:'2026-03-15',type:'trail',text:`<span class="note">LPA Trail 17k a 5:35/km.</span> FC 151ppm. <span class="pr">4 PRs de segmento.</span> Ritmo excelente para trail con desnivel. El trabajo aeróbico se nota.`},
  {id:'d9',date:'2026-03-16',type:'gym',text:`Vuelta a sala tras trail. Bíceps a 59kg, drop set de 10 reps. Sesión de mantenimiento post-esfuerzo. Cuerpo respondiendo bien a la alternancia gym/running.`},
  {id:'d10',date:'2026-03-18',type:'gym',text:`Tríceps kettlebell a 16kg × 12 — variante que carga el rango final de forma diferente. Sesión corta pero de calidad.`},
  {id:'d11',date:'2026-03-19',type:'gym',text:`Cuádriceps en backoff a 47kg. Femoral a 53kg × 8. Bíceps polea a 59kg × 10 — <span class="pr">mejora de reps respecto a sesiones previas.</span> Coordinación fuerza/resistencia en buen estado.`},
  {id:'d12',date:'2026-03-20',type:'gym',text:`<span class="pr">🔼 PR de reps: Bíceps polea 59kg × 11.</span> Tríceps a 29kg × 8. Curl martillo a 12,5kg × 7. <strong>La progresión en bíceps es consistente semana a semana.</strong>`},
  {id:'d13',date:'2026-03-23',type:'gym',text:`Sentadilla doble serie a 60kg × 8. Cuádriceps sube a 69kg × 8 — carga alta con control. Dominadas: 15 repeticiones consolidadas. <span class="note">Pierna y espalda en la misma sesión con buen rendimiento.</span>`},
  {id:'d14',date:'2026-03-24',type:'run',text:`<span class="note">5k a 5:23/km · 26:55.</span> FC 136ppm (máx 147). 395kcal. D+32m. Training Effect: Tempo aeróbico alto (3,5). Carga 106. <strong>Ritmo limpio y controlado.</strong> Base cardiovascular confirmada.`},
  {id:'d15',date:'2026-03-25',type:'gym',text:`<span class="pr">🔼 Sesión destacada del ciclo hasta la fecha.</span>

<strong>Sentadilla libre: 80kg × 8.</strong> Salto cualitativo claro. Sin dolor en ingle — punto crítico superado definitivamente. Isopol a 60kg × 12 con control perfecto en rango medio.

<strong>Cuádriceps: 47 → 59 → 65kg × 10.</strong> Progresión estructurada limpia. Próximo objetivo: 71kg.

<strong>Dominadas:</strong> 15 + 15 + 10 (fallo real). Nivel alto mantenido con fatiga bien aplicada.

<strong>Tracción diagonal: 95kg rest-pause (8+6).</strong> Ya en zona de fuerza real. Las 83kg quedaron cortas — carga identificada y corregida en la misma sesión.

<strong>Bíceps bayesian:</strong> en fase de construcción, prioridad en reps antes que peso.

<strong>Remo mancuernas: 20kg × 10+5 rest-pause.</strong> Subida de carga conseguida con buen cierre en fatiga.

<span class="note">Sin molestias en cadera. Entrando en fase de carga efectiva en varios ejercicios simultáneamente.</span>`},
  {id:'d17',date:'2026-03-26',type:'gym',text:`<strong>Sentadilla: 80kg x 9.</strong> <span class="pr">+1 rep respecto al dia anterior.</span> Mejor profundidad y sin molestias en la ingle.\n\nCuadriceps con margen claro a 59kg x 13, pero error de carga en la ultima serie (debia ser 65kg). <span class="warn">Recordar subir a 65kg la proxima vez.</span>\n\nDominadas: primera serie muy fuerte (15), caida en la segunda por fatiga.\n\n<span class="note">Sesion incompleta pero progreso solido en el bloque principal. La sentadilla sigue la trayectoria correcta.</span>`},
  {id:'d18',date:'2026-03-27',type:'gym',text:`<span class="pr">Cuádriceps consolida 72kg × 10 con margen.</span> Progresion clara semana a semana: 47 → 59 → 65 → 72kg.\n\n<strong>Dominadas sin asistencia: 20 + 18.</strong> Cambio clave de estímulo. Las dos primeras series son sólidas y limpias. <span class="pr">Nivel de fuerza en dominadas en ascenso claro.</span>\n\n<strong>Tracción diagonal: 95kg × 10</strong> — techo actual de la máquina alcanzado con buena ejecución. Rest-pause bien aplicado en el bloque superior.\n\n<span class="note">Sesión eficiente sin carga lumbar. Buena gestión de fatiga. El tren superior entra en una fase de carga real y consistente.</span>`},
  {id:'d19',date:'2026-03-30',type:'gym',text:`<strong>Sesión de fuerza, potencia y estabilidad.</strong> Peso muerto consolidado en 70kg con rest-pause efectivo. Buen equilibrio entre fuerza, pliometría y core en el mismo bloque.\n\n<span class="pr">Cuádriceps unilateral excéntrico progresa hasta 35kg × 10+10.</span> Trabajo unilateral que complementa perfectamente el patrón bilateral de la sentadilla.\n\nCore completo e integrado: dinámico, isométrico y rotacional en la misma sesión. Asimetría en oblicuos detectada y corregida durante la propia sesión.\n\n<span class="note">Alta calidad técnica sin sobrecarga lumbar. Mejora global en estabilidad y control unilateral. Sesión diferente pero muy completa.</span>`},
  {id:'d20',date:'2026-04-03',type:'senderismo',text:`<span class="pr">Mogán Senderismo — 27,93 km · D+1.898 m · 9h19.</span> Una de las salidas más exigentes del ciclo. Casi 28 km por el Parque Natural de Pilancones con casi 1.900 metros de ascenso positivo.\n\nFC media de 116 ppm durante más de 9 horas — esfuerzo sostenido de baja-media intensidad durante todo el día. 3.650 kcal totales (2.781 activas). Pérdida de líquidos estimada: 6,5 litros. Temperatura entre 20 y 33°C.\n\nTraining Effect aeróbico 3,4 con componente anaeróbico (0,7) por los tramos de pendiente pronunciada. Carga de ejercicio 104. 41.586 pasos.\n\n<span class="note">Una jornada de montaña completa. El cuerpo responde bien a este tipo de esfuerzo prolongado después de un mes sólido de entreno.</span>`},
  {id:'d21',date:'2026-04-06',type:'gym',text:`<strong>Sesión muy completa de pecho, cuádriceps y hombro.</strong>\n\nPress banca: 60kg × 8 + rest-pause. Buen estímulo de fuerza sin llegar al límite.\n\n<span class="pr">Cuádriceps 71kg × 9 — PR real confirmado.</span> El registro anterior de 72kg era un error, el verdadero PR es éste. Dropset efectivo (71→65→59kg) pese al error en la transición.\n\nPosterior hombro (face pull): ajuste clave de 11 a 23kg. <span class="pr">Muy buena progresión en una sola sesión.</span>\n\nPress militar con ajuste inteligente por protección del hombro — prioridad al control sobre la carga. Tracción vertical estable a 49.5kg.\n\nCore completo: plancha con protracción, crunch y escaladores en 3 rondas.\n\n<span class="note">Buen equilibrio entre fuerza, control y prevención. Ajustes inteligentes. Progreso claro en cuádriceps y posterior de hombro.</span>`},
  {id:'d22',date:'2026-04-07',type:'gym',text:`Press banca consolidado en 60kg × 6. La fatiga se nota en el rest-pause (5+1), pero la carga está bien establecida.\n\n<span class="pr">Cuádriceps: 71kg × 10</span> — mejor registro del día, con soltura. Dropset 71→47kg efectivo pese a no estar planificado.\n\nDeclinado constante en todas las series (12.5kg × 14), criterio estable que funciona como ancla de volumen.\n\n<span class="pr">Tracción vertical 53kg × 10</span> — progresa desde 49.5kg. Hombro posterior sólido en 23kg con margen en reps. Press militar sin molestias articulares.\n\n<span class="note">Sesión bien gestionada con fatiga acumulada. El pecho está consolidando, el cuádriceps tira fuerte y el hombro progresa con precisión.</span>`},
  {id:'d23',date:'2026-04-09',type:'gym',text:`Press banca sube a 60kg × 7 en la segunda serie, con caída a 5 en la tercera — límite real bien identificado.\n\n<span class="pr">Cuádriceps 71kg × 10</span> de nuevo, progresando con consistencia semana a semana.\n\nDeclinado estable en todas las rondas como volumen de apoyo.\n\n<span class="warn">⚠️ Sesión interrumpida por molestia en hombro al iniciar el bloque 2.</span> Decisión correcta parar antes de agravar. El bloque de core arrancó bien pero el de hombro/tracción no se completó.\n\n<span class="note">Entrenamiento incompleto pero el bloque principal fue sólido. Prioridad: revisar el hombro antes de la próxima sesión.</span>`},
  {id:'d24',date:'2026-04-10',type:'gym',text:`Sesión matutina (8:00h). <span class="pr">Press banca 60kg × 8</span> en la segunda serie — mejor registro en este ciclo. Rest-pause 5+2, límite real bien ubicado.\n\n<span class="pr">Declinado sube a 15kg × 14</span> en todas las rondas, desde 12.5kg. Progreso de carga sólido.\n\nCuádriceps consolida nivel alto: 65kg × 10 y 71kg × 10 con dropset limpio (71→65kg).\n\nTracción vertical afianzada en 53kg × 10. Press militar estable en 7.5kg con buen control articular del hombro.\n\n<span class="note">Sesión completa de alta intensidad bien gestionada. El pecho sigue progresando, el cuádriceps está en su mejor nivel del ciclo.</span>`},
  {id:'d25',date:'2026-04-13',type:'gym',text:`<span class="note">Sesión de reactivación post-virus. No es un día de rendimiento, es un día de volver bien.</span>\n\nElevación de hombros hasta 29kg × 10 con margen — hómbro sin molestias, buena señal después de los problemas recientes.\n\nTríceps polea: subida agresiva de carga (23→26→29kg) que terminó en fallo prematuro. Fatiga acumulada evidente. <span class="warn">Subida demasiado rápida — recordar progresar más gradual.</span>\n\nFemoral: tercera serie no completada por fatiga general. Límite claro bien identificado y respetado.\n\n<span class="note">Buen criterio en no forzar. Fatiga post-virus aún presente — normal. Día válido como reactivación.</span>`},
  {id:'d26',date:'2026-04-17',type:'gym',text:`Sesión de tren superior completa, sin pierna — pierna omitida intencionalmente para no comprometer la carrera.\n\n<span class="pr">Progresión homógenea en los tres patrones principales:</span> empuje (hasta 41kg×10), elevación de hombros (hasta 35kg×10) y tirante/remo (hasta 41kg×10). Series en rango alto (14/12/10) con ejecución limpia en todas las rondas.\n\nTríceps polea llega al límite correcto en la tercera serie (29kg×6) — estímulo bien aplicado sin exceso.\n\n<span class="note">Decisión inteligente: preservar las piernas para la carrera. Tren superior muy bien trabajado.</span>`},
  {id:'d27',date:'2026-04-18',type:'trail',text:`<span class="pr">Moya Trail running — 19,48 km · D+946 m · 2:52:02.</span>\n\n<span class="pr">Training Effect aeróbico 5.0 — VO₂ máximo (aeróbica alta).</span> El valor máximo posible en la escala de Garmin. FC media 144 ppm con pico en 182 ppm. Alta intensidad sostenida.\n\nAltura entre 491 y 1.063 m. 946 m de ascenso y 943 m de descenso. Perfil exigente con doble subida visible en el gráfico de elevación. Tiempo de carrera real: 1h19 corriendo / 1h32 caminando.\n\n1.872 kcal totales (1.605 activas). Temperatura 25°C. Carga de ejercicio: 242 — la mayor registrada en el ciclo en trail.\n\n<span class="note">Día después del entrenamiento de tren superior. Excelente capacidad de recuperación. El nivel aeróbico está en su punto más alto del ciclo.</span>`},
  {id:'d28',date:'2026-04-20',type:'gym',text:`Sesión matutina con estructura mixta de pecho, tríceps, espalda y pierna unilateral.\n\nPress inclinado mancuernas progresa hasta 15kg × 10. Press francés EZ (15kg total) en las tres series — trabajo de tríceps en rango largo bien ejecutado.\n\n<span class="pr">Tracción vertical supino alcanza 59kg × 7</span> — mejor registro en este patrón. Prono llega a 53kg × 6.\n\n<span class="warn">Prensa unilateral revela asimetría: pierna derecha trabaja a 50kg y pierna izquierda a 40kg.</span> Dato importante para seguimiento. La izquierda necesita trabajo específico de igualación.\n\n<span class="note">Sesión el mismo día de la medición biométrica (82,45kg). Buena calidad de trabajo a pesar del volumen alto.</span>`},
  {id:'d29',date:'2026-04-21',type:'gym',text:`Segundo día consecutivo. <span class="pr">Mejora clara en el bloque de empuje respecto al lunes:</span> press francés y barra EZ suben a 15kg × 12 y 10 en todas las series, sin la caída de reps del día anterior.\n\nTracción supino consolida 59kg en dos series (41→59kg). Prono completa a 53kg (35→53kg).\n\n<span class="pr">Prensa unilateral completada a 40kg sin asimetría</span> — ambas piernas al mismo nivel, solucionado el desbalance detectado ayer.\n\n<span class="note">Sesión consistente sin bajones entre bloques. Buen ritmo de recuperación entre sesiones consecutivas.</span>`},
  {id:'d30',date:'2026-04-08',type:'ultimate',text:`Ultimate Frisbee en Las Canteras. El GPS no miente: nube de zigzags en el mismo campo durante 1h19. 3,29 km registrados de movimiento constante (sprints, cortes, cambios de dirección).\n\nFC media 107 ppm — esfuerzo moderado-alto con picos de intensidad en cada jugada. 512 kcal. Temperatura 18°C, condiciones perfectas.\n\n<span class="note">Actividad complementaria al ciclo de fuerza. El ultimate aporta agilidad, cambios de ritmo y trabajo de campo que el gym no da.</span>`},
  {id:'d31',date:'2026-04-21',type:'run',text:`<span class="note">Carrera matutina.</span> 5k a 5:23/km en 27:00. <span class="pr">FC media 157ppm (máx 177) — la más alta registrada en carrera del ciclo.</span> Trabajo en zona de umbral aeróbico alto (Training Effect 3,8). Ritmo óptimo 4:37/km. Cadencia media 160 spm.\n\n408 kcal. Temperatura 22°C. Carga de ejercicio 126. 25 minutos de intensidad alta (×2).\n\n<span class="note">Ritmo similar a la carrera del 24/03 pero con FC significativamente más alta (+21ppm) — posiblemente fatiga acumulada de los días previos (gym lunes y martes). El cuerpo trabaja más duro al mismo ritmo.</span>`},
  {id:'d32',date:'2026-04-22',type:'gym',text:`Sesión corta (~30 min) pero eficiente. Bloque de pecho y tríceps completo con mejora respecto a días previos: press inclinado y francés EZ alcanzan 15kg × 12 y 10 en todas las series.\n\n<span class="pr">Tracción supino 53kg × 8</span> — buen registro. Prono limitado a dos series (47kg × 6) por fatiga acumulada de los tres días consecutivos.\n\nSin pierna. Sesión intencionalmente corta para no sobrecargar.\n\n<span class="note">Cuarto día consecutivo de entreno (lunes, martes gym + martes carrera + miércoles). Buena gestión al reducir volumen cuando el cuerpo lo pide.</span>`},
  {id:'d33',date:'2026-04-22',type:'ultimate',text:`Ultimate Frisbee en Las Canteras. 1h30 sobre el campo, 700 kcal. FC media 119ppm con pico en 153ppm.\n\nLos datos de detección lo dicen todo: 14 minutos corriendo, 27 caminando, 48 en inactividad (esperas entre puntos, descansos, rondas). Así es el ultimate — explosión intermitente con recuperación pasiva.\n\n<span class="note">Día doble: gym por la mañana + ultimate por la tarde. Quinto día consecutivo de actividad.</span>`},
  {id:'d34',date:'2026-04-24',type:'gym',text:`Bloque 1 consolidado con progresiones limpias: press inclinado, francés y barra EZ todos a 15kg con series de 14/12/10.\n\n<span class="pr">Tracción supino 59kg × 9 — mejor registro en este ejercicio.</span> El agarre supino sigue mejorando.\n\n<span class="warn">⚠️ Sesión interrumpida en la tercera ronda de prono (53kg × 4) por molestia en hombro.</span> Decisión correcta y acertada al cortar a tiempo. El hombro es zona de atención continuada.\n\n<span class="note">Sesión efectiva y prudente. Evitar la sobrecarga en el hombro es prioritario.</span>`},
  {id:'d35',date:'2026-04-25',type:'senderismo',text:`<span class="note">Salida de madrugada — arranque a las 4:47h.</span> San Bartolomé de Tirajana, 20,63 km en 7h23. Perfil de bajada neta pronunciada: D+688m pero D-1.236m — se baja desde la cumbre (1.080m) hasta casi el nivel del mar (70m).\n\nFC media 107 ppm durante más de 7 horas — ritmo sostenido muy bajo, eficiente. 2.040 kcal totales. Temperatura hasta 33°C en las horas de sol. 28.138 pasos.\n\nVelocidad máxima 73,5 km/h registrada — probablemente artefacto GPS en alguna zona sin cobertura.\n\n<span class="note">Jornada completa de montaña. El cuerpo aguanta bien después de una semana de alta actividad acumulada.</span>`},
  {id:'d36',date:'2026-04-27',type:'gym',text:`Circuito de 4 rondas con hómbro, banca y bíceps en progresión de carga.\n\n<span class="pr">Press hombros multipower hasta 30kg × 8</span> con réplica en ronda 4 (30kg × 7). Progresón clara desde 20kg.\n\nPress banca: 60kg × 6 en ronda 2 y 60kg × 4 en ronda 3 — fatiga acumulada del circuito visible. Back-off a 40kg × 7 en ronda 4 bien gestionado.\n\n<span class="pr">Curl predicador llega a 25kg × 6</span> en la última ronda pese a la fatiga. Progresón 12.5 →17.5 →22.5 →25kg.\n\n<span class="note">Sesión equilibrada entre intensidad y control técnico. El circuito penaliza la banca por orden pero el estímulo global es alto.</span>`},
  {id:'d37',date:'2026-04-28',type:'gym',text:`<span class="pr">Sesión muy sólida con mejora progresiva dentro del mismo día.</span>\n\n<strong>Press hombros multipower consolidado en 30kg:</strong> 10+10+7 reps — listo para subir a 35kg en la próxima sesión.\n\n<span class="pr">Press banca: progresión real dentro de la sesión — 4 → 6 → 7 reps a 60kg.</span> El cuerpo se activa con el circuito. Mejora clara respecto al día anterior.\n\nCurl predicador 25kg × 10 constante en todas las rondas — peso insuficiente ya. <span class="note">Siguiente: subir a 27.5kg.</span>\n\nCore con plancha 3 × 30 bien ejecutado.\n\n<span class="note">Ajustes identificados para la próxima sesión: hombros 35kg, predicador 27.5kg, banca mantener 60kg.</span>`},
  {id:'d38',date:'2026-04-28',type:'run',text:`5k a 5:55/km en 29:35. <span class="note">Carrera después del entreno de gym — doble jornada.</span>\n\nFC media 138ppm (máx 149) — mejor que la última carrera (157ppm al mismo ritmo). La recuperación mejora o la carga del gym fue menor hoy.\n\n397 kcal. Temperatura 23°C. Carga de ejercicio 81. 27 minutos de intensidad alta (×2). Ritmo óptimo 4:17/km.\n\n<span class="note">Buen cierre de jornada. El cuerpo responde bien al doble estímulo.</span>`},
  {id:'d39',date:'2026-04-29',type:'gym',text:`<span class="pr">Press banca 60kg × 8 — mejor serie registrada en este ciclo a esta carga.</span> La progresión dentro de las sesiones del circuito es clara: 4 → 6 → 7 → 8 reps.\n\n<span class="pr">Press hombros debuta en 35kg</span> con 7+6 reps — salto desde 30kg bien ejecutado.\n\nCurl predicador sólido en 25kg × 8 constante en ambas series de trabajo.\n\nBuena autorregulación al eliminar la 4ª ronda — 3 rondas con alta eficiencia sin fatiga innecesaria.\n\n<span class="note">El ciclo de torso con este circuito está funcionando muy bien. Progresión semana a semana en los tres ejercicios.</span>`},
];

const SEED_RAW = [
  {id:'r1',date:'2026-03-02',type:'gym',text:`Fecha: 2 marzo 2026\n\nBLOQUE PIERNA + PECHO + TRÍCEPS\n\nSentadilla: 55kg × 8 (×3)\nPress banca: 60kg × 7\nRemo Gironda: 25kg × 6 (×3)`},
  {id:'r2',date:'2026-03-03',type:'gym',text:`Fecha: 3 marzo 2026\n\nBLOQUE PIERNA + PECHO\n\nSentadilla: 60kg × 8 (×3)\nPress banca: 65kg × 8`},
  {id:'r3',date:'2026-03-04',type:'gym',text:`Fecha: 4 marzo 2026\n\nBLOQUE PECHO + ESPALDA + BÍCEPS + TRÍCEPS\n\nPress banca: 70kg × 4 — PR\nRemo Gironda: 25kg × 8 (×3)\nCurl martillo: 10kg × 6 (×3)`},
  {id:'r4',date:'2026-03-07',type:'run',text:`Fecha: 7 marzo 2026\n\nCARRERA\n\nDistancia: 14 km\nRitmo: 5:58 /km\nFC media: 161 ppm\nCalorías: 1.159 kcal`},
  {id:'r5',date:'2026-03-10',type:'gym',text:`Fecha: 10 marzo 2026\n\nBLOQUE PIERNA + PECHO\n\nHack squat: 60kg × 8 (×3)\nPress declinado: 70kg × 1`},
  {id:'r6',date:'2026-03-11',type:'gym',text:`Fecha: 11 marzo 2026\n\nBLOQUE BÍCEPS + TRÍCEPS\n\nBíceps polea: 59kg × 8 (×3) + drop set\nTríceps polea V: 29kg × 6\nCurl martillo: 12,5kg × 6`},
  {id:'r7',date:'2026-03-12',type:'gym',text:`Fecha: 12 marzo 2026\n\nBLOQUE ESPALDA + BÍCEPS + TRÍCEPS\n\nBíceps polea: 61kg × 8 — PR\nTríceps polea V: 32kg × 6\nRemo Gironda: 35kg × 10 (×2)\nCurl martillo: 15kg × 5`},
  {id:'r8',date:'2026-03-15',type:'trail',text:`Fecha: 15 marzo 2026\n\nTRAIL — LPA Trail\n\nDistancia: 17 km\nRitmo: 5:35 /km\nFC media: 151 ppm\nPRs de segmento: 4`},
  {id:'r9',date:'2026-03-16',type:'gym',text:`Fecha: 16 marzo 2026\n\nBLOQUE BÍCEPS + TRÍCEPS\n\nBíceps polea: 59kg × 8 (×3) + drop set 10 reps\nTríceps polea V: 29kg × 6\nCurl martillo: 12,5kg × 6`},
  {id:'r10',date:'2026-03-18',type:'gym',text:`Fecha: 18 marzo 2026\n\nBLOQUE BÍCEPS + TRÍCEPS\n\nBíceps polea: 59kg × 8 (×3)\nTríceps polea V: 29kg × 6\nTríceps kettlebell: 16kg × 12`},
  {id:'r11',date:'2026-03-19',type:'gym',text:`Fecha: 19 marzo 2026\n\nBLOQUE PIERNA + ESPALDA + BÍCEPS\n\nExtensión cuádriceps: 47kg × 8 (×3) — backoff\nFemoral: 53kg × 8 (×3)\nBíceps polea: 59kg × 10 (×3)`},
  {id:'r12',date:'2026-03-20',type:'gym',text:`Fecha: 20 marzo 2026\n\nBLOQUE BÍCEPS + TRÍCEPS\n\nBíceps polea: 59kg × 11 (×3) — PR reps\nTríceps polea V: 29kg × 8\nCurl martillo: 12,5kg × 7`},
  {id:'r13',date:'2026-03-23',type:'gym',text:`Fecha: 23 marzo 2026\n\nBLOQUE PIERNA + ESPALDA\n\nSentadilla: 60kg × 8 (×4)\nExtensión cuádriceps: 69kg × 8\nDominadas: 15 reps (×3)`},
  {id:'r14',date:'2026-03-24',type:'run',text:`Fecha: 24 marzo 2026\n\nCARRERA — Las Palmas de GC\n\nDistancia: 5,00 km\nRitmo medio: 5:23 /km\nRitmo óptimo: 4:41 /km\nTiempo: 26:55\nFC media: 136 ppm / FC máx: 147 ppm\nCalorías: 395 kcal\nDesnivel: +32 m / -35 m\nCadencia media: 160 spm / máx: 167 spm\nVelocidad media: 11,1 km/h / máx: 12,8 km/h\nTraining Effect: Tempo aeróbico alto (3,5)\nCarga de ejercicio: 106\nDispositivo: Garmin fēnix 6 Pro`},
  {id:'r15',date:'2026-03-25',type:'gym',text:`Fecha: 25 marzo 2026\nEntrenamiento completo\n\nPROTOCOLO INICIAL\n- Manguito rotador banda: 3×10\n- Banda elástica hombro: 3×10\n- Movilidad cadera suelo: 5×10\n- Bloque cadera: 3 isométricos (30") + 1 dinámico\n\nBLOQUE PRINCIPAL – SENTADILLA LIBRE (recorrido medio)\n60 kg × 14\n70 kg × 8\n80 kg × 8  ← PR sin dolor en ingle\nIsopol 60 kg → 12 reps\nEntre series: patada de psoas (10+10+10)\n\nBLOQUE FINAL – TRISERIE\nHip thrust: 15 / 15 / 15\nExtensión cuádriceps: 47kg×14 / 59kg×12 / 65kg×10\nDominadas (supino abierto): 15 / 15 / 10 (fallo)\n\nBLOQUE TREN SUPERIOR\nTracción diagonal: 71kg×14 / 83kg×12 / Rest-pause 95kg×8+6\nBíceps bayesian: 7,5kg×8 / 7,5kg×9 / Rest-pause 7,5kg×8+6\nRemo mancuernas: 15kg×10 / 17,5kg×10 / Rest-pause 20kg×10+5`},
  {id:'r17',date:'2026-03-26',type:'gym',text:`Fecha: 26 marzo 2026\n\nACTIVACION\n- Manguito rotador banda: 3x10\n- Banda elastica hombro: 3x10\n- Movilidad cadera suelo: 5x10\n- Bloque cadera: 3x30 + 1 dinamico\n\nBLOQUE 1 - SENTADILLA LIBRE\n60kg x 14\n75kg x 8\n80kg x 9  <- +1 rep\nDrop: 60kg x 12\nPatada de psoas: 10+10+10\nNotas: Mejor profundidad. Sin molestias en ingle.\n\nBLOQUE 2 - TRISERIE\nHip thrust: PC x 15 (x3)\nExtension cuadriceps: 47kgx14 / 59kgx13 / 59kgx12 (error carga, debia ser 65kg)\nDominadas supino abierto: PCx15 / PCx8 (fatiga)\n\nRESUMEN\n- Sentadilla 80kgx9 (+1 rep)\n- Mejor tecnica y profundidad, sin dolor ingle\n- Cuadriceps con margen, carga insuficiente en ultima serie\n- Sesion incompleta pero progreso en bloque principal`},
  {id:'r18',date:'2026-03-27',type:'gym',text:`Fecha: 27 marzo 2026\n\nACTIVACION\n- Manguito rotador banda: 3x10\n- Banda elastica hombro: 3x10\n- Movilidad cadera suelo: 5x10\n\nBLOQUE 1 - TRISERIE PIERNA\nHip thrust: PC x 15 (x3)\nExtension cuadriceps: 59kgx14 / 65kgx12 / 72kgx10 <- PR\nDominadas: PCx20 / PCx18 / PCx5 + banda x6\n\nBLOQUE 2 - TREN SUPERIOR\nTraccion diagonal: 71kgx14 / 95kgx10 / 95kgx10 / drop 95kgx10+7\nRemo mancuernas: 17,5kgx12 / 20kgx10 / 20kgx7 / drop 20kgx7+3\nBayesian: 7,5kgx10 / 7,5kgx9 / 7,5kgx8 / drop 7,5kgx8+7\n\nRESUMEN\n- Cuadriceps consolida 72kg con margen\n- Dominadas sin asistencia: cambio clave de estimulo\n- Traccion 95kg x10 (techo maquina)\n- Buena gestion de fatiga con rest-pause\n- Sin carga lumbar`},
  {id:'r19',date:'2026-03-30',type:'gym',text:`Fecha: 30 marzo 2026\n\nACTIVACION\n- Rotaciones hombro + banda: 3x10\n\nBLOQUE 1 - FUERZA + POTENCIA + CORE\nPeso muerto: 40kgx10 / 60kgx10 / 70kgx9 / drop 70kgx10+2\nPliometria: 10+10 en todas las rondas\nCore: 10 / 7 / 9 / (10+2)\n\nBLOQUE 2 - ESTABILIDAD\nIsometrico pared + pelota + gomas: 30 (x3)\nCuadriceps unilateral excentrico: 23kgx5+5 / 29kgx10+10 / 35kgx10+10\nOblicuos polea unilateral: 17kgx10+10 / 29kgx8(D)+6(I) / 29kgx6+6\n\nRESUMEN\n- Peso muerto 70kg consolidado\n- Cuadriceps unilateral hasta 35kg x10+10\n- Core completo integrado\n- Correccion asimetria oblicuos\n- Sin sobrecarga lumbar`},
  {id:'r20',date:'2026-04-03',type:'senderismo',text:`Fecha: 3 abril 2026\n\nSENDERISMO - Mogan Senderismo\nParque Natural de Pilancones\n\nDistancia: 27,93 km\nTiempo total: 9:19:37\nTiempo en movimiento: 6:25:09\nRitmo medio: 20:02 /km\nRitmo en movimiento: 13:47 /km\nRitmo optimo: 9:54 /km\nVelocidad media: 3,0 km/h\nVelocidad maxima: 6,1 km/h\nFC media: 116 ppm / FC max: 162 ppm\nCalorias totales: 3.650 kcal (2.781 activas)\nDesnivel: +1.898 m / -825 m\nAltura minima: 85 m / maxima: 1.230 m\nPasos: 41.586\nTemperatura media: 28 C (max 33 C)\nTraining Effect: Base aerobica baja (3,4 aerobico / 0,7 anaerobico)\nCarga de ejercicio: 104\nMinutos intensidad moderada: 268 min\nMinutos intensidad alta: 112 min\nPerdida de liquidos: 6.568 ml`},
  {id:'r21',date:'2026-04-06',type:'gym',text:`Fecha: 6 abril 2026\n\nPROTOCOLO INICIAL\n- Movilidad\n\nBLOQUE 1 - MULTISERIE (PECHO + CUADRICEPS + ACCESORIO)\nRonda 1: Press banca 40kgx14 / Cuad 53kgx14 / Declinado 12.5kgx14\nRonda 2: Press banca 60kgx8 / Cuad 71kgx9 PR / Declinado 12.5kgx14\nRonda 3: Press banca 60kgx6 / Cuad 71kgx8 / Declinado 12.5kgx14\n\nSERIE AVANZADA\nPress banca rest-pause: 60kgx6 + 15 + 1 (fallo)\nExtension cuadriceps dropset: 71kgx3 -> 65kgx9 (fallo) -> 59kgx3 (fallo)\nDeclinado mancuerna: 12.5kgx14\n\nBLOQUE 2 - SUPERSERIE CORE + HOMBRO (3 rondas)\nCore: Plancha + crunch + escalador 10+10\nFace pull: 11kg / 23kgx10 / 23kgx10-12\nPress militar: 10kgx7 / 7.5kgx10 / 7.5kgx8-10\nTraccion vertical: 49.5kg / 49.5kgx10 / 49.5kgx10-12\n\nRESUMEN\n- Press banca 60x8 + rest-pause\n- Cuadriceps 71kg x9 PR real confirmado\n- Posterior hombro: ajuste 11->23kg\n- Press militar: ajuste inteligente por hombro\n- Core completo\n- Sesion muy completa`},
  {id:'r22',date:'2026-04-07',type:'gym',text:`Fecha: 7 abril 2026\n\nACTIVACION\nMovilidad + hombro con bandas\n\nBLOQUE 1 - MULTISERIE\nPress banca: 40kgx14 / 60kgx6 / 60kgx6\nCuadriceps: 53kgx14 / 53kgx14 / 71kgx10\nDeclinado: 12.5kgx14 (x3)\n\nBLOQUE 2 - SERIE AVANZADA\nPress banca rest-pause: 60kgx5 / drop 60kgx5+1\nExtension cuadriceps: 71kgx8 / drop 71kgx8+47kgx10\nDeclinado: 12.5kgx14\n\nBLOQUE 3 - CORE + HOMBRO (2 rondas)\nCore: crunch 12 / escalador 10+10 / plancha 30\nPosterior hombro (face pull): 23kgx10 / 23kgx10\nPress militar: 7.5kgx10 / 7.5kgx10\nTraccion vertical: 29kgx10 / 53kgx10\n\nRESUMEN\n- Press banca 60kgx6 consolidado, fatiga en rest-pause\n- Cuadriceps 71kgx10 mejor registro del dia\n- Declinado constante (criterio estable)\n- Traccion vertical 53kgx10 progresion confirmada\n- Hombro posterior 23kg solido\n- Press militar sin molestias`},
  {id:'r23',date:'2026-04-09',type:'gym',text:`Fecha: 9 abril 2026\n\nACTIVACION\nMovilidad + bandas\n\nBLOQUE 1 - MULTISERIE\nPress banca: 40kgx14 / 60kgx7 / 60kgx5\nCuadriceps: 53kgx14 / 65kgx12 / 71kgx10\nDeclinado: 12.5kgx14 (x3)\n\nBLOQUE 2 - SUPERSERIE (INTERRUMPIDO)\nCore: inicio ok\nSesion detenida por molestia en hombro\n\nRESUMEN\n- Press banca 60kgx7, caida de reps en serie 3\n- Cuadriceps 71kgx10 solido\n- Declinado constante\n- Molestia en hombro obliga a cortar sesion\n- Entrenamiento incompleto, bloque 2 sin finalizar`},
  {id:'r24',date:'2026-04-10',type:'gym',text:`Fecha: 10 abril 2026 (8:00h)\n\nACTIVACION\nManguito rotador + bandas + movilidad\n\nBLOQUE 1 - MULTISERIE\nPress banca: 40kgx14 / 60kgx8 / 60kgx7\nCuadriceps: 53kgx14 / 65kgx10 / 71kgx10\nDeclinado: 15kgx14 (x3)\n\nBLOQUE 2 - SERIE AVANZADA\nPress banca rest-pause: 60kgx5 / drop 60kgx5+2\nCuadriceps dropset: 71kgx9 / drop 71kgx9+65kgx5\nDeclinado: 15kgx14\n\nBLOQUE 3 - CORE + HOMBRO (3 rondas)\nCore: plancha + crunch + escalador (x3)\nPress militar: 7.5kgx10 (x3)\nTraccion vertical: 41kgx14 / 53kgx10 / 53kgx10\n\nRESUMEN\n- Press banca 60kgx8 mejora clara\n- Cuadriceps 71kgx10 nivel alto consolidado\n- Declinado sube a 15kg (desde 12.5kg)\n- Traccion vertical 53kgx10 afianzada\n- Press militar estable, hombro controlado\n- Sesion completa, alta intensidad`},
  {id:'r25',date:'2026-04-13',type:'gym',text:`Fecha: 13 abril 2026 (9:00h) - Post-virus\n\nPROTOCOLO INICIAL\nManguito rotador + banda\nMovilidad hombro\n\nBLOQUE MAQUINAS\nEmpuje de pecho: completado\nElevacion hombros: 17kgx14 / 23kgx12 / 29kgx10 (comodo, margen)\nRemo Gironda: completado, sin incidencias\nTriceps polea: 23kgx14 / 26kgx12 (muy intensa) / 29kgx3 (exceso) - fatiga + subida agresiva\nExtension cuadriceps: completado\nFemoral: 1a ok / 2a ok / 3a no completada (fatiga)\n\nCONCLUSIONES\n- Entrenamiento adaptado post-virus\n- Hombro sin molestias\n- Triceps bien estimulado pese al fallo\n- Femoral marco limite por fatiga general\n- Sesion eficiente, bien regulada\n- Dia valido como reactivacion, no de rendimiento`},
  {id:'r26',date:'2026-04-17',type:'gym',text:`Fecha: 17 abril 2026\n\nEmpuje de pecho (maquina): 29kgx14 / 35kgx12 / 41kgx10\nElevacion de hombros: 23kgx14 / 29kgx12 / 35kgx10\nRemo Gironda: 29kgx14 / 35kgx12 / 41kgx10\nTriceps polea: 23kgx14 / 26kgx10 / 29kgx6\nPierna: no realizada (reserva para carrera)\n\nRESUMEN\n- Series en rango alto (12-14 / 10-12 / 8-10)\n- Progresion homogenea empuje, hombro y tiron\n- Triceps en limite correcto\n- Sesion completa tren superior\n- Sin pierna para no afectar carrera`},
  {id:'r27',date:'2026-04-18',type:'trail',text:`Fecha: 18 abril 2026 (9:00h)\n\nTRAIL RUNNING - Moya Trail running\n\nDistancia: 19,48 km\nTiempo total: 2:52:02\nTiempo en movimiento: 2:50:00\nRitmo medio: 8:50 /km\nRitmo optimo: 3:21 /km\nVelocidad media: 6,8 km/h / maxima: 17,9 km/h\nFC media: 144 ppm / FC max: 182 ppm\nCalorias totales: 1.872 kcal (1.605 activas)\nDesnivel: +946 m / -943 m\nAltura minima: 491 m / maxima: 1.063 m\nTiempo corriendo: 1:19:25 / caminando: 1:32:14\nCadencia media: 118 ppm / maxima: 233 ppm\nTemperatura media: 25 C\nTraining Effect: VO2 maximo - Aerobica alta (5.0)\nCarga de ejercicio: 242\nPerdida de liquidos: 2.114 ml`},
  {id:'r28',date:'2026-04-20',type:'gym',text:`Fecha: 20 abril 2026 (9:00h)\n\nACTIVACION\nHombros con banda elastica y manguito rotador\n\nBLOQUE 1\nPress inclinado mancuernas: 10kgx14 / 12.5kgx12 / 15kgx10\nPress frances barra EZ (15kg total): 15kgx14 / 15kgx10 / 15kgx8\nPress inclinado fuerza barra EZ: 15kgx14 / 15kgx10 / 15kgx8\n\nBLOQUE 2\nTraccion vertical prono (abierto): 35kgx14 / 53kgx8 / 53kgx7\nTraccion vertical supino (cerrado): 41kgx14 / 47kgx12 / 59kgx6\nPrensa unilateral derecha: 50kgx10 / 50kgx10 / 40kgx10\nPrensa unilateral izquierda: 40kgx10 / 40kgx10 / 40kgx10\n\nNOTAS\n- Traccion supino 59kgx6 mejor registro\n- Asimetria detectada: D 50kg vs I 40kg en prensa`},
  {id:'r29',date:'2026-04-21',type:'gym',text:`Fecha: 21 abril 2026 (manana)\n\nACTIVACION\nHombros con banda elastica\n\nBLOQUE 1 - PECHO + TRICEPS\nPress inclinado mancuernas: 10kgx14 / 15kgx12 / 15kgx10\nPress frances barra EZ: 15kgx14 / 15kgx12 / 15kgx10\nPress inclinado fuerza barra EZ: 15kgx14 / 15kgx12 / 15kgx10\n\nBLOQUE 2 - ESPALDA + PIERNA\nTraccion vertical prono: 35kgx14 / 53kgx8 / 53kgx6\nTraccion vertical supino: 41kgx14 / 59kgx6 / 59kgx6\nPrensa unilateral: 40kgx10+10 (x3, ambas piernas)\n\nRESUMEN\n- Mejora en empuje vs sesion previa\n- Traccion supino 59kgx6 consolidado\n- Prensa unilateral sin asimetria\n- Sesion consistente sin bajones`},
  {id:'r30',date:'2026-04-08',type:'ultimate',text:`Fecha: 8 abril 2026 (19:08h)\n\nULTIMATE FRISBEE - Las Canteras\n\nDistancia: 3,29 km\nTiempo total: 1:19:12\nRitmo medio: 24:05 /km (sprints + paradas)\nFC media: 107 ppm\nCalorias totales: 512 kcal\nTemperatura: 18 C\nUbicacion: Las Canteras, Las Palmas de GC`},
  {id:'r31',date:'2026-04-21',type:'run',text:`Fecha: 21 abril 2026\n\nCARRERA\n\nDistancia: ~5 km\nTiempo total: 27:00\nRitmo medio: 5:23 /km\nRitmo optimo: 4:37 /km\nVelocidad media: 11,1 km/h / maxima: 13,0 km/h\nFC media: 157 ppm / FC max: 177 ppm\nCalorias: 408 kcal (366 activas)\nDesnivel: +6 m / -10 m\nCadencia media: 160 spm / maxima: 173 spm\nTemperatura: 22 C\nTraining Effect: Umbral aerobico alto (3,8)\nCarga de ejercicio: 126\nMinutos intensidad alta: 25 min`},
  {id:'r32',date:'2026-04-22',type:'gym',text:`Fecha: 22 abril 2026 (8:20-9:00h)\n\nBLOQUE 1 - PECHO + TRICEPS\nPress inclinado mancuernas: 10kgx14 / 15kgx12 / 15kgx10\nPress frances barra EZ: 15kgx14 / 15kgx12 / 15kgx10\nPress inclinado fuerza barra EZ: 15kgx14 / 15kgx12 / 15kgx10\n\nBLOQUE 2 - ESPALDA\nTraccion vertical prono: 35kgx14 / 47kgx6 (fatiga)\nTraccion vertical supino: 41kgx14 / 53kgx8\n\nRESUMEN\n- Bloque 1 completo, volumen solido\n- Supino 53kgx8 mejora\n- Prono limitado por fatiga acumulada\n- Sesion corta ~30min, sin pierna`},
  {id:'r33',date:'2026-04-22',type:'ultimate',text:`Fecha: 22 abril 2026 (19:10h)\n\nULTIMATE FRISBEE - Las Canteras\n\nDistancia: 3,66 km\nTiempo total: 1:30:05\nTiempo en movimiento: 28:42\nTiempo corriendo: 14:15 / caminando: 27:24 / inactividad: 48:30\nRitmo medio movimiento: 7:51 /km\nRitmo optimo: 4:11 /km\nFC media: 119 ppm / FC max: 153 ppm\nCalorias: 700 kcal (560 activas)\nTemperatura: 26 C\nTraining Effect: Base aerobica baja (2,6)\nCarga de ejercicio: 47`},
  {id:'r34',date:'2026-04-24',type:'gym',text:`Fecha: 24 abril 2026 (8:32-9:07h)\n\nACTIVACION\nHombros con banda\n\nBLOQUE 1\nPress inclinado mancuernas: 12.5kgx14 / 15kgx12 / 15kgx10-11\nPress frances barra EZ: 15kgx14 / 15kgx12 / 15kgx10\nPress inclinado fuerza barra EZ: 15kgx14 / 15kgx12 / 15kgx10\n\nBLOQUE 2\nR1: Prono 35kgx14 / Supino 41kgx14\nR2: Prono 53kgx6 / Supino 59kgx9 PR reps\nR3: Prono 53kgx4 (parada por molestia hombro)\n\nCONCLUSIONES\n- Bloque 1 consolidado\n- Supino 59kgx9 mejor registro\n- Parada correcta ante molestia hombro\n- Sesion efectiva pero prudente`},
  {id:'r35',date:'2026-04-25',type:'senderismo',text:`Fecha: 25 abril 2026 (4:47h)\n\nSENDERISMO - San Bartolome de Tirajana\nParque Natural de Pilancones\n\nDistancia: 20,63 km\nTiempo total: 7:23:25\nTiempo en movimiento: 3:56:31\nRitmo medio: 21:30 /km\nRitmo movimiento: 11:28 /km\nVelocidad media: 2,8 km/h / maxima: 73,5 km/h (GPS)\nFC media: 107 ppm / FC max: 144 ppm\nCalorias: 2.040 kcal (1.351 activas)\nDesnivel: +688 m / -1.236 m\nAltura minima: 70 m / maxima: 1.080 m\nPasos: 28.138\nTemperatura media: 25 C (max 33 C)\nTraining Effect: Base aerobica baja (2,1)\nCarga de ejercicio: 27\nPerdida de liquidos: 5.189 ml`},
  {id:'r36',date:'2026-04-27',type:'gym',text:`Fecha: 27 abril 2026 (manana)\n\nACTIVACION\nMovilidad de hombro\n\nBLOQUE 1 - CIRCUITO HOMBRO + BANCA + BICEPS (4 rondas)\nR1: Press hombros 20kgx12 / Press banca 40kgx12 / Curl predicador 12.5kgx12 / Core 30+10\nR2: Press hombros 25kgx10 / Press banca 60kgx6 / Curl predicador 17.5kgx12\nR3: Press hombros 30kgx8 / Press banca 60kgx4 / Curl predicador 22.5kgx12\nR4: Press hombros 30kgx7 / Press banca 40kgx7 / Curl predicador 25kgx6 / Core\n\nRESUMEN\n- Hombros hasta 30kgx8\n- Banca 60kgx6, caida de reps por circuito\n- Curl predicador hasta 25kg\n- Core integrado\n- Sesion equilibrada`},
  {id:'r37',date:'2026-04-28',type:'gym',text:`Fecha: 28 abril 2026 (16:00-17:00h)\n\nACTIVACION\nMovilidad de hombro\n\nCIRCUITO 4 RONDAS\nR1 (aprox): Press hombros 20kgx12 / Press banca 40kgx12 / Curl predicador 12.5kgx12\nR2: Press hombros 30kgx10 / Press banca 60kgx4 / Curl predicador 25kgx10\nR3: Press hombros 30kgx10 / Press banca 60kgx6 / Curl predicador 25kgx10\nR4: Press hombros 30kgx7 / Press banca 60kgx7 / Curl predicador 25kgx10\n\nCORE: Plancha 30+5+30+5+30 (x3)\n\nCONCLUSIONES\n- Hombros 30kg consolidado -> subir a 35kg\n- Banca progreso 4->6->7 en sesion\n- Predicador 25kgx10 constante -> subir a 27.5kg\n\nAJUSTES PROXIMA SESION\n- Press hombros: 35kg\n- Curl predicador: 27.5kg\n- Press banca: mantener 60kg`},
  {id:'r38',date:'2026-04-28',type:'run',text:`Fecha: 28 abril 2026 (19:19h)\n\nCARRERA - Las Palmas de Gran Canaria\n\nDistancia: 5,00 km\nTiempo total: 29:35\nRitmo medio: 5:55 /km\nRitmo optimo: 4:17 /km\nVelocidad media: 10,2 km/h / maxima: 14,0 km/h\nFC media: 138 ppm / FC max: 149 ppm\nCalorias: 397 kcal (351 activas)\nDesnivel: +4 m / -10 m\nCadencia media: 157 spm / maxima: 169 spm\nTemperatura: 23 C\nTraining Effect: Base aerobica baja (3,2)\nCarga de ejercicio: 81\nMinutos intensidad alta: 27 min`},
  {id:'r39',date:'2026-04-29',type:'gym',text:`Fecha: 29 abril 2026 (manana)\n\nACTIVACION\nMovilidad de hombro\n\nCIRCUITO 3 RONDAS (sin 4a por autorregulacion)\nR1 (aprox): Press hombros 20kgx12 / Press banca 40kgx12 / Curl predicador 12.5kgx12\nR2: Press hombros 35kgx7 / Press banca 60kgx6 / Curl predicador 25kgx8\nR3: Press hombros 35kgx6 / Press banca 60kgx8 / Curl predicador 25kgx8\n\nRESUMEN\n- Banca 60kgx8 mejor serie del ciclo\n- Hombros 35kg debut (7+6 reps)\n- Predicador 25kgx8 constante\n- 3 rondas, alta eficiencia`},
];

export async function POST() {
  try {
    // Deduplicate by id (keep last occurrence)
    const sessionMap = {};
    SEED_S.forEach(s => { sessionMap[s.id] = s; });
    const sessionRows = Object.values(sessionMap).map(s => ({
      id: s.id, date: s.date, type: s.type,
      muscles: s.muscles || [], notes: s.notes || '', exercises: s.exercises || [],
    }));
    const { error: se } = await supabase.from('training_sessions').upsert(sessionRows, { onConflict: 'id' });
    if (se) throw new Error('sessions: ' + se.message);

    const bioRows = SEED_B.map(b => ({
      id: b.id, date: b.date, peso: b.peso, grasa: b.grasa, musculo: b.musculo,
      esq: b.esq, agua: b.agua, proteina: b.proteina, visceral: b.visceral, bmr: b.bmr, edad: b.edad,
    }));
    const { error: be } = await supabase.from('training_bios').upsert(bioRows, { onConflict: 'id' });
    if (be) throw new Error('bios: ' + be.message);

    const diaryRows = SEED_D.filter(d => d && d.id && d.date).map(d => ({
      id: d.id, date: d.date, type: d.type, text: d.text || '',
    }));
    const { error: de } = await supabase.from('training_diary').upsert(diaryRows, { onConflict: 'id' });
    if (de) throw new Error('diary: ' + de.message);

    const rawRows = SEED_RAW.filter(r => r && r.id && r.date).map(r => ({
      id: r.id, date: r.date, type: r.type, text: r.text || '',
    }));
    const { error: re } = await supabase.from('training_raw').upsert(rawRows, { onConflict: 'id' });
    if (re) throw new Error('raw: ' + re.message);

    return Response.json({
      ok: true,
      migrated: { sessions: sessionRows.length, bios: bioRows.length, diary: diaryRows.length, raw: rawRows.length }
    });
  } catch (err) {
    return Response.json({ ok: false, error: err.message }, { status: 500 });
  }
}

export async function GET() {
  const { data: s } = await supabase.from('training_sessions').select('id');
  const { data: b } = await supabase.from('training_bios').select('id');
  return Response.json({ sessions: s?.length || 0, bios: b?.length || 0 });
}
